spring:
  datasource:
    url: jdbc:mysql://localhost:3306/checkus?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  output:
    ansi:
      enabled: always

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.checkus: DEBUG

app:
  jwt:
    secret: ckdH92!ldsQ45azWXpm103OwLs94kDP3sKfmQpo8Yt32jkLa09xn1!
    expiration: 86400000  # 24시간 (밀리초)